### ISSUE TITLE
Web Socket - Fazla sayıda pairin full orderbookuna subscribe olurken "Can't connect to the server" hatası 

### ISSUE THREAD

**Issue by fatihmecidiye** [burakoner/BtcTurk.Api#1]

**Comment by burakoner** [comment]
Teker teker arada bir müddet bekleyerek subscribe ol bakalım. Tüm borsalar saniyede belli sayıda bağlantı kabul ediyorlar

**Comment by fatihmecidiye** [comment]
1 saniye bekleme koyup denedim yine aynı sorun oldu. Genellikle 15 - 16. pairden sonrasında subscribe olamıyor. RestAPI'den gelen 184 adet pairin orderbookuna subscribe olmaya çalışıyorum. Teşekkür ederim dönüşleriniz için

**Comment by burakoner** [comment]
Btcturkle görüşmen faydalı olabilir. Kodlarda bir kısıtlama yok
